services:
  # Redis for Celery
  redis:
    image: redis:7.4.2-alpine
    container_name: automagik-redis
    ports:
      - "16379:16379"
    command: redis-server --port 16379 --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "16379", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - automagik-network

  # Automagik's PostgreSQL
  automagik-db:
    image: postgres:15
    container_name: automagik-db
    environment:
      POSTGRES_USER: automagik
      POSTGRES_PASSWORD: automagik
      POSTGRES_DB: automagik
    volumes:
      - automagik-db-data:/var/lib/postgresql/data
    command: postgres -p 15432
    ports:
      - "15432:15432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U automagik -p 15432"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - automagik-network

  # Automagik API service
  automagik-api:
    image: namastexlabs/automagik-api:latest
    container_name: automagik-api
    env_file:
      - .env
    env_file:
      - .env
      AUTOMAGIK_ENV: production
      PYTHONUNBUFFERED: 1
    ports:
      - "8883:8883"
    depends_on:
      automagik-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - automagik-network

  # Automagik Worker service
  automagik-worker:
    image: namastexlabs/automagik-worker:latest
    container_name: automagik-worker
    env_file:
      - .env
    env_file:
      - .env
      AUTOMAGIK_ENV: production
      PYTHONUNBUFFERED: 1
    depends_on:
      automagik-db:
        condition: service_healthy
      automagik-api:
        condition: service_healthy
    networks:
      - automagik-network

  # Optional LangFlow service
  langflow:
    image: logspace/langflow:latest
    ports:
      - "17860:7860"
    volumes:
      - langflow-data:/data
    networks:
      - automagik-network
    profiles:
      - langflow

volumes:
  automagik-db-data:
  redis-data:
  langflow-data:

networks:
  automagik-network:
    name: automagik-network
