services:
  # Redis for Celery
  redis:
    image: redis:7.4.2-alpine
    ports:
      - "16379:16379"
    command: redis-server --port 16379 --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "16379", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - automagik-network

  # Automagik's PostgreSQL
  automagik-db:
    image: postgres:16
    environment:
      POSTGRES_USER: automagik
      POSTGRES_PASSWORD: automagik
      POSTGRES_DB: automagik
    command: postgres -p 15432
    ports:
      - "15432:15432"
    volumes:
      - automagik-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U automagik -p 15432"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - automagik-network

  # Optional LangFlow service
  langflow:
    profiles:
      - langflow
    image: langflowai/langflow:latest
    pull_policy: always
    command: langflow run --host 0.0.0.0 --port 17860
    ports:
      - "17860:17860"
    environment:
      - LANGFLOW_WORKERS=2
    volumes:
      - langflow-data:/data
    networks:
      - automagik-network

  # Automagik API service
  automagik-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python -m automagik api start
    env_file: ../.env
    ports:
      - "8883:8883"
    volumes:
      - ..:/app
    working_dir: /app
    depends_on:
      automagik-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8883/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - automagik-network
    extra_hosts:
      - "localhost:host-gateway"

  # Automagik Worker service
  automagik-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python -m automagik worker start
    env_file: ../.env
    depends_on:
      automagik-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      automagik-api:
        condition: service_healthy
    networks:
      - automagik-network
    extra_hosts:
      - "localhost:host-gateway"

volumes:
  automagik-postgres:
  langflow-data:
  redis-data:

networks:
  automagik-network:
    name: automagik-network
