services:
  # Automagik's PostgreSQL
  automagik-db:
    image: postgres:16
    environment:
      POSTGRES_USER: automagik
      POSTGRES_PASSWORD: automagik
      POSTGRES_DB: automagik
    ports:
      - "5432:5432"
    volumes:
      - automagik-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U automagik"]
      interval: 5s
      timeout: 5s
      retries: 5

  langflow-init:
    image: busybox
    command: sh -c "mkdir -p /data/langflow && chown -R 1000:1000 /data/langflow"
    volumes:
      - langflow-data:/data

  langflow:
    image: langflowai/langflow:latest
    pull_policy: always
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_WORKERS=2
    volumes:
      - langflow-data:/data

  # Automagik API service
  automagik-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python -m automagik api
    env_file: ../.env
    environment:
      DATABASE_URL: postgresql+asyncpg://automagik:automagik@automagik-db/automagik
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    working_dir: /app
    depends_on:
      automagik-db:
        condition: service_healthy

  # Automagik Worker service
  automagik-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python -m automagik worker start
    env_file: ../.env
    environment:
      DATABASE_URL: postgresql+asyncpg://automagik:automagik@automagik-db/automagik
    depends_on:
      automagik-db:
        condition: service_healthy

  # Redis service
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"

volumes:
  automagik-postgres:
  langflow-data:
